import { groqModel, geminiModel, mystralModel } from "./ai.service.js";
import cohereModel from "./cohere.setup.js";
import { StateGraph, START, END, type GraphNode, StateSchema } from "@langchain/langgraph";
import * as z from "zod";
import { createAgent, HumanMessage, providerStrategy } from "langchain";
const state = new StateSchema({
    problem: z.string(),
    solution_1: z.string(),
    solution_2: z.string(),
    judge: z.object({
        score_1: z.number(),
        score_2: z.number(),
        reason_1: z.string(),
        reason_2: z.string(),
    })
})

const solutionNode: GraphNode<typeof state> = async (state) => {
    const [cohereSolution, mystralSolution] = await Promise.all([
        cohereModel.invoke(state.problem),
        mystralModel.invoke(state.problem)
        // groqModel.invoke(state.problem)
    ])
    return {
        solution_1: cohereSolution.text || "",
        solution_2: mystralSolution.text || "" // groqSolution.text || ""
    }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const judge = createAgent({
        model: geminiModel,
        responseFormat: providerStrategy(z.object({
            score_1: z.number().min(0).max(10),
            score_2: z.number().min(0).max(10),
            reason_1: z.string(),
            reason_2: z.string(),
        })),
        systemPrompt: "You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores."
    })
    const judgeResult = await judge.invoke({
        messages: [
            new HumanMessage({
                content: `Problem: ${state.problem}\nSolution 1: ${state.solution_1}\nSolution 2: ${state.solution_2}`,
            }),
        ],
    });
    const { score_1, score_2, reason_1, reason_2 } = judgeResult.structuredResponse;
    return {
        judge: {
            score_1, score_2, reason_1, reason_2
        }
    }
}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_Node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_Node")
    .addEdge("judge_Node", END)
    .compile();

export default async function (problem: string) {
    const result = await graph.invoke({
        problem
    })
    return result;
};
